# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: datasets # dataset root dir（与你当前 datasets 结构一致）
train: images/train # train images (relative to 'path') 4 images
val: images/val # val images (relative to 'path') 4 images
# test:  # test images (optional)
# Classes (80 COCO classes)
names:
  0: Sunflower
  1: Pea
  2: Zombie
  3: Sunshine
  4: Strawberry
  ## past classes
  # 0: nomal_zombie
  # 1: conehead_zombie
  # 2: buckethead_zombie
  # 3: Sun
  # 4: Diamond
  # 5: Coin_gold_dollar
  # 6: Coin_silver_dollar